import type { NextConfig } from "next";
import path from "path";

// src/vendor/pagedjs.js is a patched copy where contains$1 always uses the
// indexOf shim (see scripts/patch-pagedjs.cjs). Regenerated by postinstall.
const patchedPagedJs = path.resolve("src/vendor/pagedjs.js");

const nextConfig: NextConfig = {
  serverExternalPackages: ["better-sqlite3", "playwright"],
  output: "standalone",
  turbopack: {
    resolveAlias: {
      pagedjs: "./src/vendor/pagedjs.js",
    },
  },
  webpack(config, { isServer }) {
    if (!isServer) {
      config.resolve.alias = {
        ...config.resolve.alias,
        pagedjs: patchedPagedJs,
      };
    }
    return config;
  },
};

export default nextConfig;
